### PR TITLE
awesome pull request using the power of github

### PR DESCRIPTION
**Pull request by sobakasu**
Hi,
i've made some changes to itunes-connect to make it work with the new itunes connect interface.
cheers
Andrew

### CODE REVIEW

**Comment by alexvollmer** [comment]
It looks like you've put some work in for this gem. I think the move to Mechanize was a smart one. That was something I had on my list for a while, but I just haven't had the time. Since I don't use the gem anymore and I'm not really maintaining it, are you interested in maintaining the official gem going forward?

**Comment by sobakasu** [comment]
sure, i'm happy to maintain it if you like.
is there anything special involved in pushing the gem, or will it just let me push a new version?
thanks for the gem by the way,  very useful
cheers
Andrew

**Comment by alexvollmer** [comment]
If you get an account on gemcutter.org I think I can assign the gem to you. Right now I have a sort of "exclusive right" on that gem name.

**Comment by sobakasu** [comment]
i'm signed up as sobakasu@gmail.com there

**Comment by alexvollmer** [comment]
I added you as an "owner" of the gem on gemcutter/rubygems. That should allow you to use the "gem push" command. I've setup itunes-connect to use the jeweler gem which gives you some nice rake tasks to manage versions, pushing to git and releasing to rubygems. If you're not already familiar with Jeweler, take a look at the docs for all the details. 

I noticed that somewhere along the way the specs were broken. It looks like this was before your changes, though. It might be worth going back and making sure those are correct—broken windows and all that.

I'll merge your changes and push to github just to keep everything consistent. If you wouldn't mind send out pull-requests before you do a release, I can make sure my repo is more-or-less consistent with yours.

Cheers, Alex

**Comment by sobakasu** [comment]
no probs, i've fixed store.rb and pushed 0.10.0 to rubygems.org.

**Comment by alexvollmer** [comment]
Thanks for fixing up the store.rb. I've pushed the commits to my master branch. Go ahead and try to release the next version using the rake tasks with jeweler.

**Comment by sobakasu** [comment]
Hi Alex,
just letting you know, I probably won't be doing any further work on this gem as we are now using the 'itc-autoingest' gem for itunes data fetching. 
cheers
Andrew

**Comment by alexvollmer** [comment]
Andrew,

Thanks for the heads-up as well as your contributions to this gem. There seem to be enough other tools that do a better job than this that I'll probably just close up shop on this project.

Cheers,

—Alex V.

**Pull request merged**
